Faster intersection operations
Kotlin/kotlinx.collections.immutable pull request #90
Opened 2020-10-19 13:21 UTC by belyaev-mikhail

Ok, this is a more major change than the previous one, but possibly more profitable. Also note that this changes public interface of `ImmutableSet`, adding `retainAll`/`intersect` pair that our domain is particularly interested in.

In addition to union, intersection, difference and containment bulk ops are all implemented using the same strategies.

`containsAll` is particularly desirable, because it has a significant speedup (up to 50x)

Benchmark results:

https://docs.google.com/spreadsheets/d/1NaMgasBhqyThazU-_TVWAK2fCcnztAQ9WCRxr9lNfUw/edit#gid=524543606

2020-10-23 00:31 UTC, qurbonzoda commented on core/commonMain/src/ImmutableCollection.kt
> +     * Returns all elements in this set that are also
in this ~set~ **collection**

2020-10-25 16:44 UTC, qurbonzoda requested changes
Please add some `containsAll` tests

2020-10-25 16:44 UTC, qurbonzoda commented on core/commonMain/src/extensions.kt
> +infix fun <E> PersistentCollection<E>.intersect(elements: Iterable<E>): PersistentCollection<E>
Kotlin intersect function has the following signature:
```
infix fun <T> Iterable<T>.intersect(other: Iterable<T>): Set<T>
```
That is the function always returns a `Set`.
Hence returning `PersistentSet<E>` here would be more consistent with stdlib.

2020-10-26 14:14 UTC, belyaev-mikhail reviewed
> Why this test became useless?

It didn't, this is a merging issue, will fix.

2020-10-26 14:14 UTC, belyaev-mikhail commented on core/commonMain/src/implementations/immutableSet/TrieNode.kt
> +private val NOVALUE = Any()
That's a possibility, didn't think about it tbh

2020-10-26 14:14 UTC, belyaev-mikhail commented on core/commonMain/src/implementations/immutableSet/TrieNode.kt
> +                if (owner == ownedBy && buffer.size < otherNode.buffer.size) buffer
The logic was as follows: Intersection size is the min of two input sizes. So we can reuse the buffer if we know for sure that it's less than the other buffer.

It should be "less or equal" actually.

But thinking of it again, seems like it does not matter, we can try to reuse the buffer in any situation.

2020-10-26 14:14 UTC, belyaev-mikhail commented on core/commonMain/src/implementations/immutableSet/TrieNode.kt
> +                    // both are just E, but different => return any one of them
Of course, this is a comment bug

2020-10-29 18:53 UTC, qurbonzoda commented on core/commonMain/src/extensions.kt
> + * @return a new persistent collection with elements in this set that are also
return a new persistent ~collection~ **set**

2020-11-11 14:15 UTC, qurbonzoda approved these changes
Great job!

2020-11-11 14:15 UTC, qurbonzoda commented on core/commonMain/src/implementations/immutableSet/PersistentHashSet.kt
> +import kotlinx.collections.immutable.internal.assert
Is it used in this file?

2020-11-12 08:45 UTC, qurbonzoda commented
Please squash the commits

2020-11-17 15:53 UTC, belyaev-mikhail commented on core/commonMain/src/implementations/immutableSet/PersistentHashSet.kt
> +import kotlinx.collections.immutable.internal.assert
Fixed

2020-11-17 15:54 UTC, belyaev-mikhail commented
Done @qurbonzoda

2020-11-18 19:29 UTC, merged

2020-11-18 19:29 UTC, qurbonzoda commented
🚀